### ISSUE TITLE
native framework/remote-run should support a TASK_STAGING timeout

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#1091]
the same issue as in https://github.com/Yelp/chronos/issues/63 - make sure we don't just leave tasks forever hanging because of docker having a bad time on agents.

**Comment by keymone** [comment]
@Rob-Johnson are we only interested in TASK_STAGING or can task get stuck on other values? do we want to specify multiple timeout options, possibly a timeout_total for when a job gets stuck in a happy state or just takes too long?

**Comment by Rob-Johnson** [comment]
this specific just covers the bug of a task never reaching TASK_RUNNING after launching it. We can cover a ``--max-run-time`` that puts an upper bound on how long a task runs in another issue.
