### ISSUE TITLE
Shelling out to flock in unit tests

### ISSUE THREAD

**Issue by mattmb** [Yelp/paasta#1239]
Because of https://github.com/Yelp/paasta/blob/master/tests/test_mac_address.py#L37-L41 I'm not able to run the tests on OSX any more. At least I need to install flock since the test shells out to flock.

However, even with https://github.com/discoteq/flock I still get a failure. @bchess do we really need to run flock for these tests? In my mind the unit tests should just test that the lock file *would* have been created?

**Comment by solarkennedy** [comment]
https://docs.python.org/2/library/fcntl.html#fcntl.flock ?

**Comment by bchess** [comment]
fcntl.flock() is probably fine, but you want to do it in a subprocess somehow - the test won't be valid if it's the same process that holds the flock() as the one that's doing the reserve_unique_mac_address() call.

The test is verifying that it correctly moves on past a mac address file that's already flocked.

**Comment by bchess** [comment]
lemme try a couple things and see if I can come up with a pure python solution
