### ISSUE TITLE
paasta local-run doesn't handle chronos jobs correctly

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#124]
Chronos surrounds the command with `sh -c '{cmd}'` (arguably a bug!), however local-run doesn't do this.

**Comment by solarkennedy** [comment]
Arg arg arg!

**Comment by asottile** [comment]
This seems to be true for marathon as well (or any command specified in marathon-XXX.yaml / chronos-XXX.yaml)

**Comment by Rob-Johnson** [comment]
I've done a little digging here:

From [the mesos docs on the docker containerizer](https://mesos.apache.org/documentation/latest/docker-containerizer):

> If shell option is set to true the Docker Containerizer will run the user’s command wrapped with /bin/sh -c which will also become parameters to the image entrypoint.

By default, the ``shell`` parameter is set to ``True`` for a Chronos Job - see [the code](https://github.com/mesos/chronos/blob/88522b574c491489662509fae09153c43bb61397/src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Jobs.scala#L74).

The [paasta code here](https://github.com/Yelp/paasta/blob/master/paasta_tools/chronos_tools.py#L228) leaves that parameter as ``True`` unless you set the ``arguments`` field in your config (I think it's a bug that you can't just set it to ``False``).

[according to the docs, marathon does the same thing](https://github.com/mesosphere/marathon/blob/20a44b643ebcffc23628dd336e08de143085004d/docs/docs/native-docker.md#command-vs-args)
