### ISSUE TITLE
add support for the startupTimeout field to chronos jobs

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#1256]
in https://github.com/Yelp/chronos/pull/65/ we added support for jobs to provide a ``startupTimeout`` field. It can be used to specify how long a task should be given to transition from TASK_STAGING to TASK_RUNNING. By default it is set to 5 minutes, but we'll need to support user-configurable timeouts in yelpsoa-configs

**Comment by solarkennedy** [comment]
I'm going to close this as wontfix
