### ISSUE TITLE
Opensource some sort of Mesos ->SmartStack (nerve) bridge

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/paasta#13]
We currently use our in-house `nerve-tools` package to configure SmartStack to match what Mesos has deployed. At the same time, the raw functions that `nerve-tools` use are actually *in* the paasta repo.

We should either open source `nerve-tools` or make a simple example script on how to configure nerve from Mesos. (a la Marathon's [servicerouter](https://github.com/mesosphere/marathon/blob/master/bin/servicerouter.py))

**Comment by EvanKrall** [comment]
This is done: https://github.com/yelp/synapse-tools and https://github.com/yelp/nerve-tools, both using https://github.com/yelp/environment_tools
