### ISSUE TITLE
Enable CORS for the REST API

### ISSUE THREAD

**Issue by magicmark** [Yelp/paasta#1373]
Requests to the web api from browsers will currently fail with an error similar to this:

```
XMLHttpRequest cannot load http://{service}:{port}/v1/services/{service}/main/status. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

This is because [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) has not been enabled by the server.

Let's add the necessary headers to allow this?

I found this middleware that might do the trick https://github.com/may-day/wsgicors

**Comment by solarkennedy** [comment]
@magicmark good to close?
