### ISSUE TITLE
setup_chronos_job does not clean up old jobs

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#146]
We currently have an itest that checks that ``setup_chronos_job`` will also remove the oldest 5 Chronos job. See the feature [here](https://github.com/Yelp/paasta/blob/master/paasta_itests/setup_chronos_job.feature#L35-L44).

The jobs chosen for deletion are the 5 oldest found by ``chronos_tools.lookup_chronos_jobs`` (see [code](https://github.com/Yelp/paasta/blob/master/paasta_tools/setup_chronos_job.py#L149-L153)).

By default, ``chronos_tools.lookup_chronos_jobs`` **ignores** disabled jobs. Given that when we bounce jobs, the disabled field is set to ``True``, old jobs will never be bounced.

The integration test first mentioned only passes because it creates 10 dummy jobs with the disabled field set to ``False``. See the template for the job [here](https://github.com/Yelp/paasta/blob/master/paasta_itests/steps/setup_chronos_job_steps.py#L58).

I've fixed this as part of #150 , this is just here for reference.

**Comment by solarkennedy** [comment]
Whoa crap. I thought for sure I totally fixed that. :(
I certainly fixed it "live" on a box when I was troubleshooting chronos bounces, but I guess I got distracted and never pushed.

I have that commit sitting on my laptop :(
