### ISSUE TITLE
Why do we have our own print function?

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#1461]
Seriously, what is `paasta_print` for, other than causing [bugs](https://github.com/Yelp/paasta/pull/1383)?

I don't remember. @mjksmith added it back in his internship, I assume for a good reason, but I think we've lost the theory of it.

**Comment by keymone** [comment]
+1, lets either drop or document reasons for having it.

**Comment by asottile** [comment]
For one, python 3 **does not flush when printing by default** (perhaps ironically, the issue/patch you linked to is actually a strong reason *to* have a wrapper, though it wasn't the original intention).

The main reasons for introducing it were:
- python2 / python3 compatibility
- printing text data when `LANG` is not set or is `LANG=C`
    - by default, python attempts to *encode* output using the "automatically detected locale"
    - In many of the cases where paasta runs (cron, marathon, docker, etc.) these environment variables aren't present
    - paasta produces textual output that is not ASCII encodable
- printing bytes is awkward in python3, there are cases where paasta has output from logs / etc. where it should be written unmodified / without decoding to output

I've written [slides about demystifying io in python 3](https://anthonywritescode.github.io/episodes-py3/04-file-io/) and plan to record a video when I get some time :)

**Comment by vkhromov** [comment]
+1 to get rid of it.

1. paasta is Python 3 only now, we don't need compatibility with Python 2.
2. We should never ever need to `print()` raw bytes, right?
3. It doesn't seem that the paasta code itself contains any non-ASCII characters, at least `find paasta_tools -name '*.py' | xargs grep --color='auto' -P -n "[\x80-\xFF]"` found nothing suspicious.

As for enforcing flushes and fixing `UnicodeEncodeError: 'ascii' codec can't encode character ...` errors, can we do something with `print()` function itself?

**Comment by asottile** [comment]
paasta itself does not have non-ascii literals, but it runs applications which produce arbitrary output

in python3.7+ the default changes from ascii to utf-8 so you might have better mileage there

the one thing to consider is you'll want `print(..., flush=True)` in most cases which might make using it a bit unfortunate

**Comment by vkhromov** [comment]
Migrating to python3.7+ indeed should help with printing unicode characters for undefined `LANG` or `LANG=C`:
```
$ cat enc.py
import sys
print(sys.version)
print(chr(246), chr(9786), chr(9787))

$ python3.6 enc.py; python3.7 enc.py
3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
ö ☺ ☻
3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
ö ☺ ☻

$ env -u LANG python3.6 enc.py; env -u LANG python3.7 enc.py
3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Traceback (most recent call last):
  File "enc.py", line 3, in <module>
    print(chr(246), chr(9786), chr(9787))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 0: ordinal not in range(128)
3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
ö ☺ ☻

$ env LANG=C python3.6 enc.py; env LANG=C python3.7 enc.py
3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Traceback (most recent call last):
  File "enc.py", line 3, in <module>
    print(chr(246), chr(9786), chr(9787))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 0: ordinal not in range(128)
3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
ö ☺ ☻
```

**Comment by vkhromov** [comment]
As for the flushing, it seems that that is an issue with `paasta_print()` itself and not with Python printing in general.

My understanding is that by default `sys.stdout` is line buffered if it's connected to a terminal (which is true for `paasta local-run`), while `paasta_print()` is fully buffered for some reason.
So,
```
$ paasta local-run --pull --cmd 'for i in 1 2 3; do date; sleep 1; done'
```
indeed delays some output after removing `flush()` call from `paasta_print()`, but the same command prints without any delays after replacing `paasta_print()` with just `print()`.

**Comment by asottile** [comment]
Here's what you should compare:

```console
$ python3 -c 'import time; print(1); time.sleep(2); print("done!")'
```

```console
$ python3 -c 'import time; print(1); time.sleep(2); print("done!")' | cat
```

The first prints `1` immediately, but the second does not.

This also acts like the first:

```console
$ python3 -u -c 'import time; print(1); time.sleep(2); print("done!")' | cat
```

**Comment by vkhromov** [comment]
That's because in the case of `| cat` `sys.stdout` isn't connected to a terminal, so it's fully buffered. `-u` is a special command line argument for which `sys.stdout` is fully *un*buffered regardless of if it connected to a terminal or not.  This is the typical behaviour for overwhelming majority of Unix apps, so we probably better mimic it for PaaSTA.

We've added `flush()` into `paasta_print() `because of #1383, my understanding is that `paasta local-run` has been running without piping it's output in that case, so replacing `paasta_print()` with `print()` should work for that case.

Anyway, we also should probably be OK by always providing `-u` to the Python interpreter.

**Comment by Rob-Johnson** [comment]
@keymone got rid of paasta_print in #2826
