### ISSUE TITLE
Prune merged branches from github.com/yelp/paasta remote

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#1478]
I've noticed that when creating a feature branch where I want to make a pull request it often takes github many minutes to notice the branch is mergeable and give me the helpful "create pull request" button.

I suspect this is due to the huge number of branches on the paasta remote (though I could be wrong!).

I've written a script that [prunes merged remote branches](https://github.com/asottile/scratch/blob/ec30d41a14448fd05ebc55d496d601d0a7843a81/python/prune-remote-branches.py) that might be helpful (it also supports `--dry-run` if you want to check what it'll do, though I've been using it for years without issue).

**Comment by solarkennedy** [comment]
Is 135 really that huge? 
Regardless I've done a big purge, ty for the easy to use script.
