### ISSUE TITLE
Speed up cluster autoscaler

### ISSUE THREAD

**Issue by matthewbentley** [Yelp/paasta#1495]
In the worst case, it can take 10 minutes for each slave it wants to kill.

There are three things that could make this faster:
1. Make draining faster/more effecient
2. Make cluster autoscaler terminate multiple slaves at a time
3. Make cluster autoscaler act on multiple resources at a time

2 is probably the easiest, while 1 would probably have the best effect (while also being the hardest).  3 is also a bit difficult, as right now the result of scaling up/down one resource can affect what the autoscaler does to the next.

2 will get it down to at most ~10 minutes per resource, and 2+3 ~10 minutes total.

**Comment by matthewbentley** [comment]
AFAICT, the way it currently works is:

For each resource:
1. Calculate a "mesos_utilization_error", which is the diff between target capacity and capacity in the pool+region cross-section (this is independant of the resource)
2. Calculate a target capacity, which is the current size of the resource scaled by the utilization_error (with minimums and maximums depending on a few factors) (this is dependent on the resource type)
3. Run `scale_resource` with the current and target capacity, which will just scale up if it needs to, or run the logic to carefully scale down
4. If scaling down, sort the hosts by how killable they are, and then drain and kill one at a time

The calculate_mesos_utilization_error can be moved outside the resource, so it gets run once and then passed to each resource.  This will allow us to scale all the resources at once.

Also, the scaling down can be done in parallel (see #1496).

**Comment by drmorr0** [comment]
The cluster autoscaler is deprecated in favor of Clusterman.
