### ISSUE TITLE
Sensu's python plugin is looking for a maintainer

### ISSUE THREAD

**Issue by mbbroberg** [Yelp/paasta#1529]
Hey! I noticed that this project uses [the Sensu plugin library for Python](github.com/sensu/sensu-plugin-python). That library is a community-maintained project and is currently lacking maintainers. I thought it'd bring it up incase anyone contributing to paasta would like to get involved. You can recommend someone (or volunteer yourself) here: https://github.com/sensu/sensu-plugin-python/issues/14. 

Thanks and cheers to all the good work you do! 

cc @solarkennedy as a heads up.

**Comment by solarkennedy** [comment]
I'm going to politely decline. It looks like there are a number of responders to the call-for-maintainers though, that is good.

I'll spread the word to the rest of the team and ask them to perk up on that issue if they are interested.

**Comment by mbbroberg** [comment]
No problem at all. Thanks for letting me know 👌
