### ISSUE TITLE
Pinned requirements in setup.py make dependency resolution hard

### ISSUE THREAD

**Issue by bplotnick** [Yelp/paasta#1804]
Pinning requirements (with `==`) in `setup.py` make it tricky if not impossible to resolve dependencies when used as a library. [Our stance](https://github.com/Yelp/requirements-tools#our-stance-on-pinning-requirements) is to generally not pin in libraries if possible, and if necessary, only loosely (e.g. `>=`) to help with dependency resolution.

Is there anything preventing us from loosening up the requirements in setup.py?

**Comment by octamois** [comment]
Any communication channel to join?
I would like to contribute at Yelp projects!

email me at anmolmishra.jiit@googlemail.com
