### ISSUE TITLE
Misleading error message with local-run -p

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#192]
```
asottile@srv2-uswest2bstagea:~$ sudo paasta local-run -p -i chronos_example -s yelp-main -c norcal-dev
Error: yelp-main.chronos_example doesn't look like it has been deployed to this cluster! (norcal-dev)
```

srv2-uswest2bstagea is in the pnw-stagea cluster

I expect the error message to be something like:

"You're not in norcal-devc --  you're in pnw-stagea!"

or for it to just work, but with the norcal-devc configuration (my service and instance are deployed in norcal-devc)

**Comment by EvanKrall** [comment]
You specifically asked to run the configuration for the norcal-dev cluster with `-c norcal-dev`. We have that option so that users in dev environments can local-run with the configuration from a different environment, or on boxes that aren't part of a paasta cluster.

**Comment by mjksmith** [comment]
Also it will work with the norcal-devc configuration if you use `-c norcal-devc` instead of `-c norcal-dev`.

**Comment by asottile** [comment]
Ah oops, typo.  copy paste error on my part it seems
