### ISSUE TITLE
If multiple marathon apps exist (e.g `paasta restart` during a bounce), crossover bounce might kill your only registered instances

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#20]
Crossover bounce starts killing old tasks as soon as there are more (happy_new_tasks + old_app_live_tasks) than the configuration asks for:

```python
        happy_count = len(happy_new_tasks)
        needed_count = max(new_config['instances'] - happy_count, 0)

        old_tasks = []
        for app, tasks in old_app_live_tasks.items():
            for task in tasks:
                old_tasks.append(task)

        return {
            "create_app": False,
            "tasks_to_drain": set(set(old_tasks[needed_count:])),
        }
```

It chooses the tasks to kill fairly arbitrarily.

This means we can get into a situation like:

1. Version A is running, with 4 tasks, all happy.
2. New config/version is pushed; we create marathon app version B.
3. version B starts 4 tasks, which all are not happy yet
4. New config/version is pushed; we create marathon app version C.
5. Bounce code sees 8 old tasks, 0 happy new tasks. 8 > 4, so we kill 4 tasks. The 4 tasks that we kill all happen to belong to version A, and the 4 that remain are still not happy yet.

**Comment by EvanKrall** [comment]
A workaround for this is to use the upthendown bounce, which won't kill anything until all new instances are happily in the load balancer. Unfortunately, that means you have to have enough spare resources on your cluster to spin up an entire new copy of your app.

**Comment by jolynch** [comment]
@EvanKrall wait is this fixed?

**Comment by EvanKrall** [comment]
Should be? Did you see something that suggested otherwise?
