### ISSUE TITLE
Control tags besides start/stop are all interpreted as stop.

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#223]
The change in #190 created tags like `paasta-norcal-prod.main-20160203T005046-deploy`. This results in a `desired_state` of `deploy` in deployments.json for the service in question. Then [marathon_tools interprets `deploy` as `!= "start"`](https://github.com/Yelp/paasta/blob/7be0ed698bc26b8eb840348ad001718e95539b18/paasta_tools/marathon_tools.py#L197), so the service in question is stopped.

We should potentially:
 - whitelist desired_state to start or stop in generate_deployments_for_service.py
 - blacklist `...-deploy` tags in generate_deployments_for_service.py
 - have the reimplementation of #190 create a different format of tag that doesn't get interpreted as a state change.

**Comment by nhandler** [comment]
My vote would be for the whitelist. It feels like the safest solution. We also aren't going to be adding new types of tags that will require updating this list too often. I am fine actioning this when I fix up #190

**Comment by solarkennedy** [comment]
How about the code that is responsible for looking up the desired state, only match the regex it is expecting? `.*(start|stop)$`

That way we can add more tags at will, and the right code can look out for them? (docker image code can look for the deploy tag, desired_state can look for start/stop, some future certification code can look for the certify tag, etc.
