### ISSUE TITLE
Rename /state.json endpoint in conjunction with mesos 0.24.x to 0.25.x upgrade

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#232]
In the mesos notes on upgrading from 0.24.x to 0.25.x, they note that the `/state.json` endpoint is becoming `/state`. We use this endpoint in at least one place: https://github.com/Yelp/paasta/blob/67793d2fe99a7f503add185fb8ad92b1a039e436/paasta_tools/mesos_tools.py#L276

This will need to be fixed when we do the mesos upgrade.

Note: A few other endpoints are being renamed, but I was not able to find references to them from a quick grep through our code.

**Comment by mjksmith** [comment]
There's also a couple references that appear in Yelp puppet if you run `git grep state.json`
