### ISSUE TITLE
Document all the environment variables paasta adds to containers

### ISSUE THREAD

**Issue by mjksmith** [Yelp/paasta#2574]
The env variables `PAASTA_RESOURCE_(CPUS|MEM|DISK|GPUS)`, `PAASTA_GIT_SHA` and `PAASTA_INSTANCE_TYPE` are added to the environment here: https://github.com/Yelp/paasta/blob/65661ee6b77442f5f1fd16e95be7d2d46b8dc59b/paasta_tools/utils.py#L539

but are not documented here: https://paasta.readthedocs.io/en/latest/yelpsoa_configs.html#common-settings

**Comment by solarkennedy** [comment]
Got it in PAASTA-15453
