### ISSUE TITLE
Add ARM64 support to Paasta

### ISSUE THREAD

**Issue by odidev** [Yelp/paasta#2904]
Hi Team,

I am interested to add ARM64 support to Paasta. 
I have checked that the package is primarily set up for AMD64, and installs binaries and uses docker images for AMD64. I have tried replacing some of the binaries and Docker images with arm64 tags and did some related changes, but still have encountered many issues in Travis-CI jobs for ARM64.
It will be really helpful if ARM64 support is added to the package. Do you have any plans for the same? 
Also, it will be really helpful if you can share any blockers for this activity.

Please share your opinion on this.

**Comment by drmorr0** [comment]
Unfortunately we don't have any plans to add ARM64 support to PaaSTA.  I am curious to know more about your use case?  If you paste some of the errors you are seeing in the thread we can _maybe_ offer some pointers or code hints, but no promises.

**Comment by odidev** [comment]
**Hi** @drmorr0 

**Below are the issues encountered :**

1.  A test is failing for installing docker-ce via Dockerfile :
~~~
E: Version '17.03.2~ce-0~ubuntu-xenial' for 'docker-ce' was not found
~~~
Please find my Travis logs here: <https://travis-ci.com/github/odidev/paasta/jobs/380377783#L1287>

Version 17.03.2 is not available for arm64, hence Travis is failing to install it.



2.  Another test is failing for below error :
~~~
Failed to fetch http://repos.mesosphere.com/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)
~~~
Travis is downloading amd64 binaries from <http://repos.mesosphere.com/>, but arm64 binaries are not present in this link. Hence Jobs are failing. Here are the logs: <https://travis-ci.com/github/odidev/paasta/jobs/380377785#L954>


3.  Another test is failing to build cluster for ‘travis-k8s-test’ :
~~~
docker run error: command "docker run --hostname travis-k8s-test-worker2 --name travis-k8s-test-worker2 --label io.k8s.sigs.kind.role=worker --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.k8s.sigs.kind.cluster=travis-k8s-test --network bridge kindest/node:v1.17.2@sha256:59df31fc61d1da5f46e8a61ef612fa53d3f9140f82419d1ef1a6b9656c6b737c" failed with error: exit status 125
~~~
Here are the logs: <https://travis-ci.com/github/odidev/paasta/jobs/380377789#L828>

The ‘kindest/node’ image is available for amd64 only. Please find the link here: <https://hub.docker.com/r/kindest/node/tags>


4.  Another test is failing with below logs :
~~~
dh_strip: error: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/paasta-tools/opt/venvs/paasta-tools/lib/python3.8/site-packages/msgpack/_cmsgpack.cpython-38-x86_64-linux-gnu.so returned exit code 1
~~~
Here is the link to the errored job: <https://travis-ci.com/github/odidev/paasta/jobs/380377788#L2416>


* Here is a link to all the 9 Travis jobs for ARM64, 5 of them are failing: <https://travis-ci.com/github/odidev/paasta>

Please let me know if any more information is required.

**Comment by Rob-Johnson** [comment]
we'l come back to this if we ever need to support ARM
