### ISSUE TITLE
PaaSTA leaves rogue processes running on remote hosts when interrupted.

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#30]
We reverted our original implementation of this in #28 so this is to follow up and try again.

If a paasta cli command is interrupted, it will leave any stray processes launched on remote hosts. For example if the user runs `paasta status` and then interrupts during execution, there may be a rogue `paasta serviceinit status` running on a master. We should make an effort to cleanup what we can before exiting.

**Comment by solarkennedy** [comment]
I'm going to close this as won'tfix, as we are moving towards the API-based approach.
