### ISSUE TITLE
Document impact of DST on chronos schedules

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#334]
While chronos is capable of dealing with this properly, it requires configuring the schedule correctly. We should update our documentation to make this more clear. For instance, a timezone of PST functions differently than a timezone of America/Los_Angeles. Likewise, an interval of 24h is different than one of 1d (per https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by nattofriends** [comment]
PST isn't a timezone, at least not on Debian

**Comment by mittonk** [comment]
So, should I be using `America/Los_Angeles`, or something else entirely, for that timezone?

**Comment by solarkennedy** [comment]
We are going to be deprecating chronos, so I'm going to wont-fix.
