### ISSUE TITLE
Nice-to-haves for `paasta status -v`

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#358]
Some suggestions courtesy @jeffseif:
1. When a historical batch started running (ideally, beyond just the previous one)
2. How long a historical batch took to run (ideally, beyond just the previous one)
3. When the batch is next scheduled to run
4. What the invocation will be for the next scheduled run
5. The entire stdout and stderr for a historical run (ideally, beyond just the previous one)

Some of these are hard, some of these are easier. (chronos doesn't store 1 or 2; mesos only keeps stdout/stderr for a while.) 3 and 4 we can compute.

We should probably break out the more involved ones into their own tickets.

**Comment by Rob-Johnson** [comment]
I'm going to close this, given tron is the tool we use for interacting with batches now
