### ISSUE TITLE
Use docker containerizer in itests

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#373]
When running PaaSTA, we set the mesos containerizer to `docker`. However, we do not specify a containerizer currently for our itests. This causes it to default to `mesos`. To ensure we are testing a setup like the one we actually run, we should update the itests to use the `docker` containerizer. This will also likely allow us to stop specifying `--launcher=posix` when running mesos.

**Comment by EvanKrall** [comment]
This is somewhat tricky, as the tests run in a container. We'd need to volume-mount the docker socket or run [docker-in-docker](https://github.com/jpetazzo/dind).

**Comment by mjksmith** [comment]
@EvanKrall The docker-in-docker people don't recommend you use it for CI. http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
It looks like bind-mounting the docker socket is the way to go

**Comment by matthewbentley** [comment]
Can I take a stab at this? It looks like we'd need to bind mount the docker socket into the mesos slaves, and tell mesos to use docker (in `paasta_itests/docker-compose.yml`, I think).

**Comment by matthewbentley** [comment]
So when I make the following change:
```
diff --git a/paasta_itests/docker-compose.yml b/paasta_itests/docker-compose.yml
index a4a6935..b7e99fb 100644
--- a/paasta_itests/docker-compose.yml
+++ b/paasta_itests/docker-compose.yml
@@ -18,8 +18,13 @@ mesosslave:
     - zookeeper
   environment:
     -CLUSTER: testcluster
-  command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512; disk(*):100" --credential=/etc/mesos-slave-secret --launcher=posix'
+  command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512; disk(*):100" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker'
   hostname: mesosslave.test_hostname
+  privileged: true
+  volumes:
+    - /var/run/docker.sock:/var/run/docker.sock
+    - /usr/bin/docker:/usr/bin/docker

 marathon:
   build: ../yelp_package/dockerfiles/itest/marathon/
diff --git a/paasta_itests/steps/bounces_steps.py b/paasta_itests/steps/bounces_steps.py
index f3b51b5..1e4a654 100644
--- a/paasta_itests/steps/bounces_steps.py
+++ b/paasta_itests/steps/bounces_steps.py
@@ -96,7 +96,7 @@ def when_there_are_num_which_tasks(context, num, which, state):
             if len(app.tasks) - happy_count >= context.max_tasks:
                 return
         time.sleep(0.5)
-    raise Exception("timed out waiting for %d %s tasks on %s; there are %d" %
+    raise Exception("timed out waiting for %s %s tasks on %s; there are %s" %
                     (context.max_tasks, state, app_id, app.tasks))
```

I get the result in the attached files
 - paasta_itests.txt = output of `tox -e paasta_itests`
 - compose.txt = output from `docker-compose logs -f`

[compose.txt](https://github.com/Yelp/paasta/files/308120/compose.txt)
[paasta_itests.txt](https://github.com/Yelp/paasta/files/308119/paasta_itests.txt)

**Comment by EvanKrall** [comment]
Probably we'll have to modify the marathon app definition we're sending, in paasta_itests/steps/bounces_steps.py, to include a `container` key.

Eventually we should actually use `MarathonServiceConfig.format_marathon_app_dict` to create the marathon app JSON.

**Comment by EvanKrall** [comment]
yeah, from compose.txt:

```
[32mmesosslave_1   |[0m I0609 23:34:30.823935    20 docker.cpp:1009] No container info found, skipping launch
```
