### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#376]
In order to enable auto-scaling (or manual scaling, or destructive maintenance like docker upgrades) of Paasta clusters, we need for tasks to be proactively moved off of boxes that will go down soon.

Here's my proposal:

1. Use [Mesos's Maintenance primitives](http://mesos.apache.org/documentation/latest/maintenance/) to mark nodes as going down. Even though [Marathon doesn't support them](https://github.com/mesosphere/marathon/issues/2414), I think this is the "right way" to indicate this status, and maybe Marathon will support them in the future. For the purposes of this issue, I'm going to call boxes in draining mode "at-risk", to avoid confusion with Paasta's task draining.
2. Have setup_marathon_job inspect the existing applications and count the number of tasks running on at-risk boxes, and scale up the application by that number. Once new tasks are healthy, drain at-risk tasks.
    1. Marathon may spin up those new tasks on an at-risk box. Since you can't modify constraints of running Marathon applications without Marathon restarting everything, we can't get Marathon to not do this unless something else eats up those resources (see 3.) However, this isn't a huge deal - the next time setup_marathon_job runs, we'll spin up more; eventually, at-risk boxes would be full and all new instances would have to go somewhere else.
3. To help with 2i, setup_marathon_job (or some other cron job) could try to make [dynamic reservations](https://mesos.apache.org/documentation/latest/reservation/) for all remaining resources on an at-risk box, reserving them for a bogus [role](https://mesos.apache.org/documentation/latest/roles/). We'd also need to unreserve these resources once the box is no longer at-risk.
4. Write helper scripts that can:
    1. mark a box as draining
    2. wait until it's fully drained
    3. undrain the box.
    4. A wrapper that does all 3 of the above and runs a specified commands, for doing e.g. docker restarts.

**Comment by EvanKrall** [comment]
Step #3 of the above would prevent chronos from running new tasks on draining boxes; existing tasks would not be killed. That seems like sort of the ideal for chronos.

**Comment by nhandler** [comment]
I played around with this a bit. I was able to schedule a maintenance (which didn't really do anything since the frameworks don't support it yet). I was then able to start the maintenance. This not only stopped all tasks on the slave, it stopped the entire mesos-slave process. As a result, when I sent the REST request indicating maintenance was over and instructing it to bring the host up again, it didn't do anything. I had to manually restart the mesos-slave process to get things back to normal.

**Comment by solarkennedy** [comment]
Whoa, that doesn't sound right. The mesos-slave completely stopped?

**Comment by mjksmith** [comment]
@solarkennedy from http://mesos.apache.org/documentation/latest/maintenance/

'When maintenance is triggered by the operator, all agents on the machine are told to shutdown. These agents are subsequently removed from the master which causes tasks to be updated as TASK_LOST.'

Idk if mesos-slave should have stopped but all the tasks dying is correct. It looks like we want 'Drain Mode'.

**Comment by nhandler** [comment]
Just to be clear, I was explicitly testing whether putting a box into 'down' mode would work. So killing the tasks was expected. Having the mesos-slave process stop was not expected, and I will be investigating this some more.

**Comment by solarkennedy** [comment]
Yea, `down` mode sounds the same as kill -USR1 (thing that graceful_mesos_shutdown uses)

**Comment by EvanKrall** [comment]
I think the strategy listed in the description will still work if we consider boxes to be "at-risk" if there is a maintenance scheduled for less than N minutes from now. We could get fancy and have N be configurable per service, but we could also just use 10 or 20 for now.

**Comment by analogue** [comment]
Why not focus resources on adding this support to marathon? Will this work be obviated when marathon eventually supports maintenance mode primitives?

**Comment by EvanKrall** [comment]
1. scala is hard
2. Even if we solved marathon#2414, then marathon#712 would still be a problem - draining a box would kill tasks without pulling them out of smartstack first.

**Comment by solarkennedy** [comment]
Also, handling maintenance at this level means that it will work with marathon/chronos/spark/seagull/etc in general (the resource hoarding).
