### ISSUE TITLE
only require a date to chronos-rerun if there is something to be interpolated

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#420]
In the case that there is no interpolation to be done, then a date shouldn't be required for ``paasta rerun``. A default is a little dangerous, given that it's a meaningful part of the command in the case where interpolation is required - lets detect if interpolation is required, and require a date if so.

**Comment by Rob-Johnson** [comment]
@giuliano108 this was done in #419 wasn't it?

**Comment by giuliano108** [comment]
> this was done in #419 wasn't it?

Indeed, closing.
