### ISSUE TITLE
Come up with some way of overcoming the behaviour set in mesos/chronos#660

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#426]
This is a pretty nasty feature - I wonder if we get round this for free by being "declarative" - In the case a user deletes a parent job, they'd have to explicitly delete it from the `parents` list of any dependent jobs to pass `paasta validate`, and so we'd end up recreating the dependent job with the updated list of parents rather than it being converted to a scheduled one.

**Comment by solarkennedy** [comment]
easylink mesos/chronos#660

**Comment by solarkennedy** [comment]
I'm going to close this as wontfix
