### ISSUE TITLE
Build Xenial packages

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#476]
We should make a Xenial build pipeline at some point.

**Comment by nhandler** [comment]
I was planning to look into this as soon as Mesosphere started publishing xenial packages in their repositories.

**Comment by EvanKrall** [comment]
We'll probably want to do #477 at the same time as this -- since Xenial doesn't come with python2.7 by default, it becomes more important to list the python2.7 dependency.

**Comment by asottile** [comment]
@EvanKrall @nhandler this is done now and can be closed
