### ISSUE TITLE
comparison table updated against autodesk/ochopod

### ISSUE THREAD

**Issue by opaugam** [Yelp/paasta#49]
hey - could we get the comparison page updated with data-points relating to https://github.com/autodesk-cloud/ochopod ? I would gladly pull-req something but I'm not really qualified to speak about Paasta..

**Comment by solarkennedy** [comment]
The comparison table is not meant to be an exhaustive list comparing paas's. I mostly focused on projects that where the development of the paas was the "primary product". In this case, ochopod is not a primary asset to Autodesk. Contrast this to Amazon's ECS or Hashicorp's Nomad. It isn't much as "is it open source" as much as "is this product's primary audience other engineers? Or was it built for themselves?"

It is true the ochopod is similar to paasta in the sense that it builds of off many of the same components, but I don't really want to start a precedent of adding every paas under the sun to this doc.

Likewise I wouldn't expect Nomad's docs to compare themselves to paasta. We just built this for ourselves and we not really in the "paas" business. Does that make sense?

**Comment by opaugam** [comment]
oh it totally makes sense :)
