### ISSUE TITLE
Unify logging behavior

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/paasta#490]
From #482, we setup logging in `main` situations, set log levels, etc.

In our lib classes we also setup logging (sometimes) and use the same `__main__` logger, so it gets the same log level and such.

@Rob-Johnson recommends adding a null handler in the library classes so they can be used as-is, and allowing them to use `__name__` so that the log entry shows up with the "correct" class name.

@Rob-Johnson I'm trying to make it so the class "inherits" the same log level that was set in `main`, but it isn't working.

```
# Lib class
log = logging.getLogger(__name__)
mainlog = logging.getLogger('__main__')
log.addHandler(logging.NullHandler())
# Prints 30 (warn) all the time, because I think that is what it is set at import time
print mainlog.getEffectiveLevel()
log.setLevel(mainlog.getEffectiveLevel())
```

This seems a bit harder than it "should" be?

**Comment by Rob-Johnson** [comment]
ah ok - this is what you need:

foo.py
```
log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())

def hi():
   log.debug('hi')
   return 1
```

my_script.py
```
import foo
import logging

log = logging.get_logger(__name__)

def parse_args():
    # return the args object here

def main():
    args = parse_args()
    if args.verbose == 1:
       logging.basicConfig(level=logging.DEBUG)
    print foo.hi()

if __name__ == __main__():
   main()
```

You should see the debug line from foo.py called here
