### ISSUE TITLE
Make tests less verbose

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#503]
As side-effects of our tests, lots of log entries get printed to the terminal. Since we test failure situations, lots of this text is red and mentions errors or other problems. This can make it a bit confusing when looking through the test output to try and understand why they failed.

It would be nice to clean this up a bit so the output is less verbose (or possibly allow setting the verbosity with an ENV variable).

**Comment by solarkennedy** [comment]
Can we have tox capture?
https://pytest.org/latest/capture.html

Cause behave does that thing where it will only spit out what came from stdout on failure?

**Comment by asottile** [comment]
For pytest, if you remove `-s` it will be quiet.
