### ISSUE TITLE
Support cfs_quota_us / cfs_period_us

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#504]
Recently, Mesos added an option:

> `--[no]-cgroups_enable_cfs`  Cgroups feature flag to enable hard limits on CPU resources via the CFS bandwidth limiting subfeature. (default: false)

This is really intriguing, since it provides a way to hard-cap containers. We're not sure whether Mesos would set the appropriate options on Docker, but Marathon allows us to pass arbitrary command line flags to `docker run` [via the `container.docker.parameters` field](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps), and docker has command line flags for this:

```
  --cpu-period                    Limit CPU CFS (Completely Fair Scheduler) period
  --cpu-quota                     Limit CPU CFS (Completely Fair Scheduler) quota
```

@solarkennedy and I played around with this, and it does appear to work:

```
krall@dev5-devc:~/ $ docker run -d --cpu-period 100000 --cpu-quota 20000 busybox sh -c 'yes >/dev/null'
481e13359f87800a5979d09f6c0caa3f8b54754bdfe2d6103cd16563c6000366
krall@dev5-devc:~/ $ docker stats --no-stream 481e13359f87800a5979d09f6c0caa3f8b54754bdfe2d6103cd16563c6000366
CONTAINER                                                          CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
481e13359f87800a5979d09f6c0caa3f8b54754bdfe2d6103cd16563c6000366   20.12%              409.6 kB / 135.2 GB   0.00%               648 B / 648 B       319.5 kB / 0 B
krall@dev5-devc:~/ $
```

We were thinking it would be useful to add some parameters to marathon.yaml:

 - `cfs_period_us`: would set `--cpu-period` pretty much directly, but would default to 100000 (100ms), which is the default in the kernel.
 - `cpu_burst_pct`: Would set --cpu-quota through some math, but would default to 100, allowing services to use up to 2x their CPU allocation before getting throttled. (The CPU shares setting that Mesos/docker is already setting would still apply).

Math: `cfs_quota_us = cpus * cfs_period_us * (100 + cpu_burst_pct) / 100`.

I think as described here, this would be a pretty straightforward change but could provide some big wins in preventing services from impacting each other, particularly during startup.

@Rob-Johnson You're interested in isolation things. Does this seem reasonable to you? Do you want to take this?

**Comment by EvanKrall** [comment]
@matthewbentley Want to take this?

**Comment by matthewbentley** [comment]
What does `cpus` in `cfs_quota_us = cpus * cfs_period_us * (100 + cpu_burst_pct) / 100` refer to?

**Comment by EvanKrall** [comment]
Oh, sorry, that refers to the `cpus` setting in marathon.yaml (or chronos.yaml): http://paasta.readthedocs.io/en/latest/yelpsoa_configs.html#marathon-clustername-yaml, accessible via `self.get_cpus()` on a MarathonServiceConfig (or ChronosJobConfig or anything else that subclasses InstanceConfig)
