### ISSUE TITLE
Get rid of "special" files in /etc/paasta

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#515]
Our strategy for loading system configs is generally to read files from /etc/paasta in SystemPaastaConfig, and a particular config key can exist in any file in this directory.

However, a few places in the codebase, we read files like /etc/paasta/marathon.json or /etc/paasta/chronos.json, and look for specific keys in those files, like `user`, `password`, and `url`.

We should read the marathon / chronos cluster information through SystemPaastaConfig, and make these files less special. This would entail changing the file format from 

```
{
  "user": "admin",
  "password": "something",
  "url": [
    "box1:5052",
    "box2:5052"
  ]
}
```

to

```
{
  "marathon_server": {
    "user": "admin",
    "password": "something",
    "url": [
      "box1:5052",
      "box2:5052"
    ]
  }
}
```

**Comment by solarkennedy** [comment]
Yes!

**Comment by EvanKrall** [comment]
@matthewbentley want to take this on?

**Comment by matthewbentley** [comment]
A quick look through the code shows that these special cases are currently:
- chronos.json
- performance-check.json
- marathon.json

This doesn't look too hard from here. Although this would be a breaking change, as current configurations for those three files would have to be re-written?

**Comment by EvanKrall** [comment]
Yeah, we'll need to have Puppet write out both new and old configs for a while.
