### ISSUE TITLE
Write docs on how bounces + draining work

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#529]
Currently we've got some docs on the config options available to service authors: http://paasta.readthedocs.io/en/latest/workflow.html#bouncing

Unfortunately we don't have any docs on how bounces work, nor any docs on drain methods. We should explain how this works behind the scenes, for the benefit of service authors, new developers on paasta, and operators of paasta clusters.

Touch on:
- What setup_marathon_job does, which things it observes about the environment
- how draining works
- how autoscaling works
- (once #521 is merged) how maintenance mode is handled

**Comment by Rob-Johnson** [comment]
fixed in https://github.com/Yelp/paasta/pull/538
