### ISSUE TITLE
Use "real" configs for itests

### ISSUE THREAD

**Issue by matthewbentley** [Yelp/paasta#576]
eg, `paasta_itsests/steps/bounces_steps.py:49` hard codes a config.  We should have itests that test the config parsing/generation, either by modifying existing itests or creating new ones to do so.  Modifying the existing itests would also mean additions to the configs (eg #564, #567) wouldn't need to also change the itest setups.

Relates to #373, as it will be a lot easier to use real configs if we use docker to run the tests.

**Comment by matthewbentley** [comment]
This would also help prevent diff like [this](https://github.com/Yelp/paasta/files/309553/docker.txt).

**Comment by EvanKrall** [comment]
I'm attempting a refactor of setup_marathon_job and I'm incidentally doing this.
