### ISSUE TITLE
paasta logs should have --instance option

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#585]
It would be nice to be able to look at logs for a specific instance.

**Comment by solarkennedy** [comment]
@ammaraskar can you do this if you have free time?

**Comment by ammaraskar** [comment]
Ideally this needs a refactoring of the `logs` command, right now there's so many filtering arguments just being passed as kwargs, it is not going to work as we keep adding more and more things to filter by.

**Comment by solarkennedy** [comment]
@mjksmith can you take a look at this one? I don't mind the kwargs, personally.

The use case here is that a user is troubleshooting why their batch didn't work, say, from last night, and it would be helpful if they can see only the logs they care about. (This is especially true for services with tons of instances, like yelp-main)

At the same time the alert hints should be adjusted to give users the exact paasta logs command 
https://github.com/Yelp/paasta/blob/aebf1fcb3dfa36f25954834f609ac5be604c7975/paasta_tools/check_chronos_jobs.py#L128
(missing from here) https://github.com/Yelp/paasta/blob/aebf1fcb3dfa36f25954834f609ac5be604c7975/paasta_tools/check_marathon_services_replication.py#L179
