### ISSUE TITLE
setup_marathon_job.py is incomprehensible, badly needs refactoring

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/paasta#596]
The dependency-injection style we used in setup_marathon_job.py has gotten out of hand as we added more features to the bounce.

I'd like to refactor that code to make more sense. Steps I'm planning to take:
1. "un-factor" setup_marathon_job by inlining deploy_service / do_bounce into setup_service. This will produce one giant procedure that reads top-to-bottom, instead of the very strange ordering that we currently have.
2. Pull individual actions (e.g. redrain all draining tasks) into their own functions.
3. Potentially group these actions further into high-level steps, like "observe", "plan", "execute".

**Comment by Rob-Johnson** [comment]
closing given {{setup_marathon_job}} will soon be removed
