### ISSUE TITLE
Config file merging

### ISSUE THREAD

**Issue by mattmb** [Yelp/paasta#605]
At the moment when we load config files the last one wins:
https://github.com/Yelp/paasta/blob/master/paasta_tools/utils.py#L750

We're generating multiple files for each spot fleet request associated with a cluster and we end up only loading one. I think we should probably deep merge if we don't think that will break anything else...

**Comment by solarkennedy** [comment]
Oh whoops, I thought that it would merge them all correctly in this case because they have unique "ids"?
But yea, deep_merge.

**Comment by mattmb** [comment]
Fixed in #611
