### ISSUE TITLE
RFC: Initial secrets support

### ISSUE THREAD

**Issue by matthewbentley** [Yelp/paasta#633]
The way I plan for this to work:
- paasta-slaves pull secrets onto the filesystem on boot, to `some_dir/service_name/secret_name`, for each service and secret. This is done through some unspecified means, although in reality it will be a python script communicating with Vault
- Paasta adds two config options: `external_secret_location` and `internal_secret_location` (names tbd)
- When starting a container, bind mount `external_secret_location/service_name` to `internal_secret_location`
- Add logic to volumes option parsing to prevent mounting anything from `external_secret_location`, as it contains secrets from other services

**Comment by matthewbentley** [comment]
Another option: have system paasta configs that whitelist what can be volume mounted into a container.

This would look something like:
```json
[
    {"path": "/nail/bulkdata", "mode": "ro"},
    {"path": "/nail/etc/services/{service_name}", "mode": "ro"},
    {"path": "/foo/bar", "mode": "rw"}
]
```
allowing the `path`s to be python format strings, that get passed at least the service name.

**Comment by matthewbentley** [comment]
To expand on how that relates to secrets, the BAR service could then specify that it wants to mount `/nail/etc/secrets/BAR`, but it cannot try to mount `/nail/etc/secrets/FOO`.

**Comment by solarkennedy** [comment]
For the "initial" support, I still recommend that paasta be "secret agnostic", reusing the existing extra_volumes functionality. Once we are comfortable with the methodology and the deployment mechanism we can bake in more security things, like the whitelist and stuff.

**Comment by Rob-Johnson** [comment]
closing - we have secrets now
