### ISSUE TITLE
Upgrade marathon to 1.3.0

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#639]
We are currently using 1.1.1 in our itests. We should upgrade to the latest version.

**Comment by nhandler** [comment]
There is no reason to bother with the 1.1.2 upgrade anymore. As we speak, they are publishing the final version of 1.3.0, and they support upgrading from 1.1.0 directly to 1.3.0 (since there was never a 1.2.0). I am going to update this issue to be for upgrading to 1.3.0

**Comment by solarkennedy** [comment]
Closing as we are using 1.4 now.
