### ISSUE TITLE
Cannot fetch index base URL http://pypi.yelpcorp.com/

### ISSUE THREAD

**Issue by pmann91** [Yelp/paasta#77]
Getting "Cannot fetch index base URL http://pypi.yelpcorp.com/" error as the url is not accessible while running "make itest_trusty".

**Comment by solarkennedy** [comment]
Yea... this isn't super great, that target is actually yelp-specific. Assigning to @nhandler for triage and improvement.

**Comment by LMAdrien** [comment]
Hello Where can i find the scribereader 0.1.25. I have tried on https://libraries.io/github/Yelp/paasta and other url.  Thx

**Comment by nhandler** [comment]
Published #90 to make it a bit more clear that the target will currently not work outside of Yelp.

**Comment by LMAdrien** [comment]
To solve the dependence scribereader and other packages missing the only solution is the exclures. Some files need to be edited.

 1. For the tox.ini file 
deleted the line that contains dependencies

-  :private:scribereader==0.1.30
-    :private:yelp-cgeom==1.3.1
-    :private:yelp-logging==1.0.37
-    -r/work/requirements.txt
- install_command= pip install --allow-external scribereader {opts}     {packages}
- commands = ./build-manpages.sh

 2.  For the /yelp_package/extra_requirement file
    deleted the single line 
 -  scribereader==0.1.30
  
 3. remove line in file yelp_package/itest/ubuntu.sh
     man -f paasta-$command

**Comment by nhandler** [comment]
Closing this now that we've isolated the Yelp-specific make targets and fixed the errors when building PaaSTA on non-yelp infrastructure.
