### ISSUE TITLE
paasta may start running newly built application without deploying

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#781]
We believe this happened today with an internal application (seagull-app)

A few things have to go wrong here but I think this is a pretty severe bug:
- The service build is non-deterministic (unpinned packages, javascript assets via uglify, etc.)
- The tests + itests are insufficient for full verification of the application

Consider a python application which satisfies the above:
- The build is non-deterministic (such as an unpinned dependency in requirements.txt)
- The tests are insufficient (not 100% coverage, not testing interaction with unpinned dependency).
1. Master is at `deadbeef`
2. Build of application (with `dependency@1.0.0`) succeeds and image `paasta-deadbeef` is pushed to the registry
3. Application is marked for deployment in a staging environment
4. Application is verified in a staging environment and marked for deployment in a production environment
5. Time passes... dependency version 2.0.0 is released
6. Nightly build of application (with `dependency@2.0.0`) succeeds and image `paasta-deadbeef` is pushed to the registry
7. Production instances are cycled out
8. New instances begin running with broken `dependency@2.0.0`

I hope I'm incorrect here, but observing the seagull-app pipeline this seems to be the case

**Comment by solarkennedy** [comment]
No, you are correct :(

Internally this issue is tracked as PAASTA-239.

**Comment by chriskuehl** [comment]
https://github.com/Yelp/paasta/pull/1179 fixed this -- images already on the registry won't be overwritten anymore, so it can't happen anymore that your image is changed out from under you without a new SHA.
