### ISSUE TITLE
wrong version of mesos.interface being installed

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#81]
```
robj@home:~/paasta_tools  python setup.py install
...
Processing dependencies for paasta-tools==0.16.0
Searching for mesos.interface>=0.20.0
Reading https://pypi.python.org/simple/mesos.interface/
Best match: mesos.interface 0.25.0.linux-x86-64
Downloading https://pypi.python.org/packages/any/m/mesos.interface/mesos.interface-0.25.0.linux-x86_64.tar.gz#md5=fa35f214cca0dde9548b12b8307374fb
Processing mesos.interface-0.25.0.linux-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-ySyTBk/mesos.interface-0.25.0.linux-x86_64.tar.gz
```

we specify ``mesos.interface==0.22.1.2`` in requirements.txt, so I'll do some digging to see why it thinks we want ``mesos.interface>=0.20.0``

**Comment by Rob-Johnson** [comment]
if you run

```
robj@home:~/paasta_tools  pip install .
..
```
The install is successful.  However, the version of mesos.interface is still incorrect (0.25.0 is installed, rather than 0.22.1.2 specified in requirements.txt). mesos.cli requires ``mesos.interface>=0.20.0``, which I suspect is to blame here.

**Comment by EvanKrall** [comment]
This is expected behavior. If you want the specific versions, pip install -r requirements.txt
