### ISSUE TITLE
getting started docs are incorrect outside of Yelp

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#82]
from https://paasta.readthedocs.org/en/latest/installation/getting_started.html#paasta-tools

```
git clone git@github.com:Yelp/paasta.git
# Assuming you are on Ubuntu Trusty
make itest_trusty
sudo dpkg -i dist/paasta_tools*.deb
```

``make itest_trusty`` fails outside of Yelp (#77), so is super unhelpful for those looking at PaaSTA for the first time.

**Comment by EvanKrall** [comment]
This is closed with #337
