### ISSUE TITLE
Disable coloring when not a tty

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#84]
`watch paasta status -c ...` still contains ANSI escape characters.

The usual way to do this is to allow a `--color` cli option `('auto', 'never', 'always')` and with `'auto'` respect `.isatty()`

You can see my implementation here:
https://github.com/pre-commit/pre-commit/blob/d17063862/pre_commit/color.py#L30-L42
https://github.com/pre-commit/pre-commit/blob/d17063862/pre_commit/main.py#L82-L85

**Comment by solarkennedy** [comment]
This is a tad tricky because `paasta status` works by calling a something else via ssh. We could make `paasta status` do the smartness and then pass that through to `paasta_serviceinit` though.
