### ISSUE TITLE
`ThrowingArgumentParser` is a slightly misleading name

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#842]
https://github.com/Yelp/paasta/blob/0e882a089250be3daa6207dc7d9920937e532407/paasta_tools/cli/cli.py#L29

I guess it does technically throw `SystemExit` but so does the baseclass.  I think a better name would probably be `PrintsHelpOnErrorArgumentParser`?

**Comment by samjjc** [comment]
i can get on this

**Comment by asottile** [comment]
Seems this is already done:

https://github.com/Yelp/paasta/blob/55eeff0aed00c6f5b340d332257f38b273c6b069/paasta_tools/cli/cli.py#L30
