### ISSUE TITLE
paasta mark-for-deployment --wait-for-deployment: option to not add a tag?

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#889]
This command seems very weird.  When I just want to wait for a specific revision to be on an environment how would I do that?  Right now I can't do that without the side-effect of adding a tag.

Does it make sense to split this into a `mark-for-deployment` and a `wait-for-deployment` command?  Do we complicate `make-for-deployment` further with a `--no-tag` option?

**Comment by asottile** [comment]
As a clever workaround (_**hack**_):

```bash
paasta mark-for-deployment \
    --git-url . \
    --commit $(git rev-parse HEAD) \
    --deploy-group stagef \
    --wait-for-deployment \
    --service www_pages
```

`--git-url .` causes this to add a tag to the local repository, as long as that doesn't get pushed, no new remote tag \o/

**Comment by solarkennedy** [comment]
Yea I figured we would eventually have a `wait-for-deployment` for scripts that just want to do the second part.

**Comment by oktopuz** [comment]
'paasta wait-for-deployment' implemented.
https://github.com/Yelp/paasta/pull/915
