### ISSUE TITLE
0.16.1 Release Broke 'paasta status'

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#91]
The 0.16.1 release appears to have broken 'paasta status'. @dichiarafrancesco, can you look into this? @solarkennedy can probably provide some more details.

**Comment by dichiarafrancesco** [comment]
@nhandler sorry can you be more specific? because i tried in my dev-box `paasta status -c norcal-devc -s chunkserv -v` and i received the expected result.

**Comment by solarkennedy** [comment]
@dichiarafrancesco that is because we rolled back. Here is an example output when it was broken:

```
$ paasta status -s lucy -c norcal-prod -v
Pipeline: [36mhttps://jenkins.yelpcorp.com/view/services-lucy[0m

cluster: norcal-prod
  instance: [34mpolyglotwest_0[0m
    Git sha:    8bcd77ea
    
  instance: [34mpolyglotwest_1[0m
    Git sha:    114e631e

...
```

As if there was no output at all from paasta_serviceinit

**Comment by dichiarafrancesco** [comment]
solved in this pull reqeust: https://github.com/Yelp/paasta/pull/100
