### ISSUE TITLE
Generate a services.json as well as services.yaml

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#950]
Some "opinionated individuals" (^) would rather not yaml :)

Seems it would be an easy addition to `paasta_tools.generate_services_yaml`

I mostly want this so I can use python with just stdlib

**Comment by solarkennedy** [comment]
We have an opportunity to make a new format that is hopefully better than the old one.

Plus I would like to have room for specifying a socket file, maybe optional ssl ?

@asottile do you preferences or ideas on the structure of this json?

**Comment by asottile** [comment]
I don't really have any opinions on the structure -- the current structure of the yaml is fine with me.
