### ISSUE TITLE
ETA for bounce is like a windows 98 progress bar

### ISSUE THREAD

**Issue by asottile** [Yelp/paasta#978]
```

 80% (4 of 5) |#######################      | Elapsed Time: 0:05:14 ETA: 0:00:22  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:51:23 
 80% (4 of 5) |#######################      | Elapsed Time: 0:05:28 ETA: 0:00:23  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:51:42 
 80% (4 of 5) |#######################      | Elapsed Time: 0:05:47 ETA: 0:00:36  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:52:01 
 80% (4 of 5) |#######################      | Elapsed Time: 0:06:06 ETA: 0:00:37  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:52:18 
 80% (4 of 5) |#######################      | Elapsed Time: 0:06:23 ETA: 0:01:04  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:52:38 
 80% (4 of 5) |#######################      | Elapsed Time: 0:06:43 ETA: 0:02:24  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:52:55 
 80% (4 of 5) |#######################      | Elapsed Time: 0:07:00 ETA: 0:02:29  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:53:17 
 80% (4 of 5) |#######################      | Elapsed Time: 0:07:22 ETA: 0:02:28  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:53:31 
 80% (4 of 5) |###########   | Elapsed Time: 0:07:36 ETA: 18516633 days, 2:26:40  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:53:49 
 80% (4 of 5) |##########   | Elapsed Time: 0:07:54 ETA: 18464433 days, 13:33:19  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:54:06 
 80% (4 of 5) |##########   | Elapsed Time: 0:08:11 ETA: 18908863 days, 10:13:20  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:54:24 
 80% (4 of 5) |##########   | Elapsed Time: 0:08:29 ETA: 18713406 days, 22:40:00  error_pages.main on norcal-prod is still bouncing, 2 versions running
16:54:33 
100% (5 of 5) |############################| Elapsed Time: 0:08:48 ETA:  0:00:00Complete: error_pages.main on norcal-prod looks 100% deployed at 2 instances on 79951bec
16:54:33 Deploy to norcal-prod complete! (instances: main)
```

Looking forward to waiting 51,269 years for my last instance to bounce :)

**Comment by oktopuz** [comment]
I think by default it should report some basic stats that can be easily read and can be streamed to irc.

I would hide current output unless --verbose is set, and would remove the progress bar as well.

@solarkennedy, any thoughts on this?

**Comment by solarkennedy** [comment]
Well, I thought the free ETA on the progress bar was cool, but @asottile is right, it probably isn't adding anything. 

But I don't want to get rid of the whole progress bar. The timestamps on when each component finished bouncing is good, right?

**Comment by solarkennedy** [comment]
Also keep in mind that I just used an off-the-shelf progress bar python module so I didn't have to reinvent the wheel. Giving the thing more datapoints (telling it about tasks, not just whether the instance has bounced or not) will allow it to make better predictions. Additionally giving it *smooth* datapoints for a crossover bounce will help. (like 100 old and 0 new is 0% done, 50 old and 50 new is 50% done, and so on), but the math will need to be able to accommodate the situation where there is 100% old and 100% new too.

**Comment by jglukasik** [comment]
We might be able to use the tqdm module for this: https://github.com/tqdm/tqdm#nested-progress-bars

**Comment by chriskuehl** [comment]
I'd be +1 on either deleting the progress bar, or making it understand individual containers (not instances).

Pushmasters get really confused now because the progress that the bar shows is barely related to the % of code that has deployed. I might have 0% of instances fully deployed (what the progress bar will show), but really be 90% done with the deployment. It's pretty misleading.
