### ISSUE TITLE
test_mark_for_deployment occasionally hangs

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/paasta#993]
@oktopuz can you help us out here please? I think this is something we discussed in the original PR https://github.com/Yelp/paasta/pull/972#discussion-diff-97113954R427 - we're seeing the tests occasionally hang indefinitely

**Comment by oktopuz** [comment]
Sure. I'm on it.

**Comment by oktopuz** [comment]
Fixed by #995
